[package]
name = "q3_pyramidd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
assert_cmd = "2"

[dev-dependencies]
predicates = "2"  